#logging:
#  pattern:
#    #设置控制台输出的日志格式
#    console: "%d - %msg%n"
#  #设置文件路径
#  #用path: D:\Javacode\sell\log\ 会在log文件夹下面生成Spring.log文件
#  file: D:\Javacode\sell\log\sell.log
#  #设置级别
#  level:
#    #设置所有类的方法
#    root: error
#    #单独设置一个类的方法,优先级更高
#    com.wechatorder.sell: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.86.131/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell

wechat:
  #授权
  myAuthorizeApp: wx605280fa0b466faa
  myAuthorizeAppSecret: bc81d0238d4196edf77d8b2debf0a5cb

  #公众账号
  mpAppId: wxd898fcb01713c658 #已改
  mpAppSecret:
  #开发平台，卖家扫码登陆

  #支付/商户号
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  #发起支付不需要证书，退款要
  keyPath: D:\WechatOrdering\resorce\h5.p12
  #异步通知
  notifyUrl: http://kevinsell.nat300.top/sell/pay/notify